FROM node:18 AS builder

WORKDIR /app

COPY frontend/package.json .
RUN npm install

COPY frontend .
RUN npm run build

FROM nginx:alpine
WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY --from=builder /app/build .

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
